sudo: false

language: php

php:
  - 5.6

script: phpunit --coverage-text

addons:
  apt:
    packages:
    - gearman-job-server
    - libgearman-dev

install:
  - pecl install gearman-1.0.3
  ## Composer
  - composer install